#-------------------------------------------------------------------------------
# .travis.yml
# Author: Alan D. Snow, 2017
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# System specifications for Travis CI
#-------------------------------------------------------------------------------
language: c
os:
  - linux
env:
  - TRAVIS_PYTHON_VERSION="2.7"
  - TRAVIS_PYTHON_VERSION="3.5"
  - TRAVIS_PYTHON_VERSION="3.6"
matrix:
  fast_finish: true
  allow_failures:
    - env: TRAVIS_PYTHON_VERSION="3.5"
    - env: TRAVIS_PYTHON_VERSION="3.6"
notifications:
  email: false

before_install:
#-----------------------------------------------------------------------------
# Install minconda
#-----------------------------------------------------------------------------
- wget -O miniconda.sh http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH=$HOME/miniconda/bin:$PATH
- conda config --set always_yes yes
- conda update conda python
#-----------------------------------------------------------------------------
# Create conda environment
#-----------------------------------------------------------------------------
- conda create -n test python=$TRAVIS_PYTHON_VERSION
- source activate test
- conda install pylint flake8

install:
- cd $TRAVIS_BUILD_DIR

script:
- flake8
- pylint tethysapp setup.py
