#-------------------------------------------------------------------------------
# .travis.yml
# Author: Alan D. Snow, 2017
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# System specifications for Travis CI
#-------------------------------------------------------------------------------
language: c
os:
  - linux
env:
  - TRAVIS_PYTHON_VERSION="2"
  - TRAVIS_PYTHON_VERSION="3"
matrix:
  fast_finish: true
  allow_failures:
    - env: TRAVIS_PYTHON_VERSION="3"
notifications:
  email: false

before_install:
#-----------------------------------------------------------------------------
# Install Tethys Platform
#-----------------------------------------------------------------------------
- wget https://raw.githubusercontent.com/tethysplatform/tethys/release/scripts/install_tethys.sh
- bash install_tethys.sh -b release
- conda config --set always_yes yes
- conda update conda python
#-----------------------------------------------------------------------------
# Activate Tethys Conda Environment & Install Dependencies
#-----------------------------------------------------------------------------
- t
- conda install xarray netcdf4
- conda install pylint flake8

install:
- cd $TRAVIS_BUILD_DIR
- python setup.py develop

script:
- flake8
- pylint tethysapp setup.py
